steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'REACT_APP_API_BASE=${_REACT_APP_API_BASE}'
      - '-t'
      - '${_IMAGE_TAG}'
      - '.'
images:
  - '${_IMAGE_TAG}'
substitutions:
  _REACT_APP_API_BASE: ''
  _IMAGE_TAG: ''
